### ISSUE TITLE
Stack overflow on Windows

### ISSUE THREAD

**Issue by leo60228** [zmwangx/rust-ffmpeg-sys#9]
This is happening in my CI: https://github.com/leo60228/hsmusicifier/runs/1751852366?check_suite_focus=true

I use Linux, so I'm not able to debug this further currently.

**Comment by leo60228** [comment]
`main` in `build.rs` is using just over the maximum of 2M of stack. I couldn't figure out why this is the case, but adding this to `.cargo/config` works around the issue:
```toml
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:4194304"]
```
